name: Dependabot auto-merge Demo Projects
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string

jobs:
  perl-sdk-tests:
    if: ${{ contains(inputs.repository, 'perl-sdk') }}
    uses: ./.github/workflows/perl-sdk-test.yml
    secrets: inherit
    permissions:
      contents: read

  python-sdk-tests:
    if: ${{ contains(inputs.repository, 'python-sdk') }}
    uses: ./.github/workflows/python-sdk-test.yml
    secrets: inherit
    permissions:
      contents: read

  php-sdk-tests:
    if: ${{ contains(inputs.repository, 'php-sdk') }}
    uses: ./.github/workflows/php-sdk-test.yml
    secrets: inherit
    permissions:
      contents: read

  java-sdk-tests:
    if: ${{ contains(inputs.repository, 'java-sdk') }}
    uses: ./.github/workflows/java-sdk-test.yml
    secrets: inherit
    permissions:
      contents: read

  node-sdk-tests:
    if: ${{ contains(inputs.repository, 'node-sdk') }}
    uses: ./.github/workflows/node-sdk-test.yml
    secrets: inherit
    permissions:
      contents: read

  go-sdk-tests:
    if: ${{ contains(inputs.repository, 'go-sdk') }}
    uses: ./.github/workflows/go-sdk-test.yml
    secrets: inherit
    permissions:
      contents: read

  blesta-ispapi-tests:
    if: ${{ contains(inputs.repository, 'blesta-ispapi') }}
    uses: ./.github/workflows/blesta-ispapi-test.yml
    secrets: inherit
    permissions:
      contents: read

  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Auto-merge Dependabot PR
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    needs:
      - perl-sdk-tests
      - python-sdk-tests
      - php-sdk-tests
      - java-sdk-tests
      - node-sdk-tests
      - go-sdk-tests
      - blesta-ispapi-tests
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        # (fixes, features but not major upgrades!)
        run: gh pr merge --auto -d -r "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.RTLDEV_MW_CI_TOKEN }}
