name: Linting & Coverage
on:
  workflow_call:

jobs:
  lint:
    name: 🧪 Linting
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ vars.RTLDEV_MW_CI_GOLANG_VERSION }}"
          check-latest: true
      - name: Super Linter Code Base
        uses: github/super-linter/slim@v6
        env:
          FILTER_REGEX_INCLUDE: "/*|/scripts/*|updateVersion.sh|**/*.go"
          FILTER_REGEX_EXCLUDE: "**/*_test.go"
          DEFAULT_BRANCH: master
          VALIDATE_GO: true
          VALIDATE_BASH: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run build
        run: go build .
      - name: Run vet
        run: go vet .

  test_matrix:
    name: 🧪 Testing
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    needs: lint
    strategy:
      matrix:
        go-version: ${{ fromJson(vars.RTLDEV_MW_CI_GOLANG_MATRIX) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Run build
        run: go build .
      - name: Run test
        run: ./scripts/test-go.sh

  dependabot:
    needs:
      - test_matrix
      - lint
    if: ${{ github.actor == 'dependabot[bot]' && (success() || needs.lint.result == 'success' || needs.test_matrix.result == 'success') }}
    uses: ./.github/workflows/auto-merge-dependabot-pr.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
