name: Linting & Coverage
on:
  workflow_call:

jobs:
  lint:
    name: 🧪 Linting & Testing
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          check-latest: true
          python-version: ${{ vars.RTLDEV_MW_CI_PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip -V
          pip install --upgrade -e .
      - name: Python version
        run: |
          echo "Python version: "
          echo ${{ vars.RTLDEV_MW_CI_PYTHON_VERSION }}
      - name: Super Linter Code Base
        uses: github/super-linter/slim@v6
        env:
          FILTER_REGEX_INCLUDE: "/hexonet/*|/scripts/*|updateVersion*.sh|setup.py"
          DEFAULT_BRANCH: master
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_BASH: true
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Coverage Report
        run: "./scripts/coverage.sh"

  dependabot:
    needs: lint
    if: ${{ github.actor == 'dependabot[bot]' && (success() || needs.lint.result == 'success') }}
    uses: ./.github/workflows/auto-merge-dependabot-pr.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
