name: Release
on:
  workflow_call:

jobs:
  tests:
    uses: ./.github/workflows/perl-sdk-test.yml
    secrets: inherit
    permissions:
      contents: read

  release:
    name: Release @ ${{ vars.RTLDEV_MW_CI_OS }}
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    needs: tests
    permissions:
      contents: write
      issues: write
      deployments: write
    container:
      image: perldocker/perl-tester:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup NodeJS ${{ vars.RTLDEV_MW_CI_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.RTLDEV_MW_CI_NODE_VERSION }}
          check-latest: true
          cache: "npm"
      - name: APT Packages
        run: apt install -y perl-doc ctags perltidy lsb-release
      - name: SW Versions
        run: |
          lsb_release -a
          node -v
          npm -v
          perl -V
      - name: install perl dependencies
        run: |
          cpm install -g --no-test --show-build-log-on-failure --cpanfile cpanfile
          perl Makefile.PL
          make
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RTLDEV_MW_CI_TOKEN }}
          CPAN_USER: ${{ secrets.CPAN_USER }}
          CPAN_PASSWORD: ${{ secrets.CPAN_PASSWORD }}
          TEAMS_NOTIFICATION_URI: ${{ secrets.RTLDEV_MW_CI_NOTIFICATION_URI }}
          COMMIT_SHA: ${{ github.sha }}
        # we are root as of perl-tester image, npx won't invoke with root rights
        run: ./node_modules/.bin/semantic-release
