name: Linting & Coverage
on:
  workflow_call:

jobs:
  lint:
    name: 🧪 Linting
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Super Linter Code Base
        uses: github/super-linter/slim@v5
        env:
          FILTER_REGEX_INCLUDE: "/src/*|/tests/*"
          DEFAULT_BRANCH: main
          VALIDATE_PHP: true
          VALIDATE_PHP_PHPCS: true
          VALIDATE_PHP_PHPSTAN: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_matrix:
    name: 🧪 Testing
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    needs: lint
    permissions:
      contents: read
    strategy:
      matrix:
        php-version: ${{ fromJson(vars.RTLDEV_MW_CI_PHP_MATRIX) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Dependencies::PHP${{ matrix.php-version }}
        run: |
          echo "$HOME/.composer/vendor/bin" >> "$GITHUB_PATH"
          composer update
      - name: Code Validation
        run: composer run-script test