name: Linting & Coverage
on:
  workflow_call:

jobs:
  lint:
    name: 🧪 Linting
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Dependencies::PHP${{ vars.RTLDEV_MW_CI_PHP_VERSION }}
        run: |
          echo "$HOME/.composer/vendor/bin" >> "$GITHUB_PATH"
          composer update
      - name: Super Linter Code Base
        uses: github/super-linter/slim@v7
        env:
          FILTER_REGEX_INCLUDE: "/src/*|/tests/*|updateVersion.sh"
          DEFAULT_BRANCH: master
          VALIDATE_PHP: true
          VALIDATE_PHP_PHPCS: true
          VALIDATE_PHP_PHPSTAN: true
          VALIDATE_BASH: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_matrix:
    name: 🧪 Testing
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    needs: lint
    permissions:
      contents: read
    strategy:
      matrix:
        php-version: ${{ fromJson(vars.RTLDEV_MW_CI_PHP_MATRIX) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - name: Install Dependencies::PHP${{ matrix.php-version }}
        run: |
          echo "$HOME/.composer/vendor/bin" >> "$GITHUB_PATH"
          composer update
      - name: Code Validation & Coverage
        env:
          TESTS_USER_HEXONET: ${{ secrets.RTLDEV_MW_CI_USER_HEXONET }}
          TESTS_USERPASSWORD_HEXONET: ${{ secrets.RTLDEV_MW_CI_USERPASSWORD_HEXONET }}
          TESTS_USER_CNR: ${{ secrets.RTLDEV_MW_CI_USER_CNR }}
          TESTS_USERPASSWORD_CNR: ${{ secrets.RTLDEV_MW_CI_USERPASSWORD_CNR }}
          TESTS_ROLE_CNR: ${{ secrets.RTLDEV_MW_CI_ROLE_CNR }}
          TESTS_ROLEPASSWORD_CNR: ${{ secrets.RTLDEV_MW_CI_ROLEPASSWORD_CNR }}
        run: composer run-script test

  dependabot:
    needs:
      - test_matrix
      - lint
    if: ${{ github.actor == 'dependabot[bot]' && (success() || needs.lint.result == 'success' || needs.test_matrix.result == 'success') }}
    uses: ./.github/workflows/auto-merge-dependabot-pr.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
