name: Release
on:
    workflow_call:
        inputs:
            repository:
                required: true
                type: string

jobs:
    sdks-release:
        if: ${{ contains(inputs.repository, '-sdk') }}
        uses: ./.github/workflows/release-sdks.yml
        with:
            repository: ${{ inputs.repository }}

    blesta-ispapi-release:
        if: ${{ contains(inputs.repository, 'blesta-ispapi') }}
        uses: ./.github/workflows/blesta-ispapi-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    gulp-release-notification-plugin-release:
        if: ${{ contains(inputs.repository, 'gulp-release-notification-plugin') }}
        uses: ./.github/workflows/gulp-release-notification-plugin-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    php-idna-translator-release:
        if: ${{ contains(inputs.repository, 'php-idna-translator') }}
        uses: ./.github/workflows/php-idna-translator-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    semantic-release-replace-release:
        if: ${{ contains(inputs.repository, 'semantic-release-replace') }}
        uses: ./.github/workflows/semantic-release-replace-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write
