name: Release
on:
    workflow_call:
        inputs:
            repository:
                required: true
                type: string

jobs:
    perl-sdk-release:
        if: ${{ contains(inputs.repository, 'perl-sdk') }}
        uses: ./.github/workflows/perl-sdk-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    python-sdk-release:
        if: ${{ contains(inputs.repository, 'python-sdk') }}
        uses: ./.github/workflows/python-sdk-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    php-sdk-release:
        if: ${{ contains(inputs.repository, 'php-sdk') }}
        uses: ./.github/workflows/php-sdk-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    java-sdk-release:
        if: ${{ contains(inputs.repository, 'java-sdk') }}
        uses: ./.github/workflows/java-sdk-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    node-sdk-release:
        if: ${{ contains(inputs.repository, 'node-sdk') }}
        uses: ./.github/workflows/node-sdk-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    go-sdk-release:
        if: ${{ contains(inputs.repository, 'go-sdk') }}
        uses: ./.github/workflows/go-sdk-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    blesta-ispapi-release:
        if: ${{ contains(inputs.repository, 'blesta-ispapi') }}
        uses: ./.github/workflows/blesta-ispapi-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    gulp-release-notification-plugin-release:
        if: ${{ contains(inputs.repository, 'gulp-release-notification-plugin') }}
        uses: ./.github/workflows/gulp-release-notification-plugin-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    php-idna-translator-release:
        if: ${{ contains(inputs.repository, 'php-idna-translator') }}
        uses: ./.github/workflows/php-idna-translator-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write

    semantic-release-replace-release:
        if: ${{ contains(inputs.repository, 'semantic-release-replace') }}
        uses: ./.github/workflows/semantic-release-replace-release.yml
        secrets: inherit
        permissions:
            contents: write
            issues: write
            deployments: write
