name: Linting & Coverage
on:
  workflow_call:

jobs:
  dependabot:
    uses: ./.github/workflows/auto-merge-dependabot-pr.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write